name: frontend-ci

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master         # Push events on master branch
      #- dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and test frontend using npm
      ## webpack will populate version to UI if APP_VERSION is present so we grab it from build.gradle
      run: |
        VERSION="$(git describe --abbrev=0) $(date +%F_%T)"
        echo "Building new frtonend version $VERSION"
        npm ci
        APP_VERSION="$VERSION" npm run webpack:prod --if-present
        ls -l  build/resources/main/static
      env:
        CI: true
        MAPBOX_GL_ACCESS_TOKEN: ${{ secrets.MAPBOX_GL_ACCESS_TOKEN }}

    - name: Configure AWS credentials for bucket access
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy webapp archive to S3
      # minimum: compileKotlin
      run: |
        echo "GITHUB_SHA=$GITHUB_SHA" >$buildinfo
        echo "GITHUB_REF=$GITHUB_REF" >>$buildinfo
        # echo "BUILD_DATE=$(date +%F_%T)" >>$buildinfo
        echo "APP_VERSION=$(git describe --abbrev=0) $(date +%F_%T)" >>$buildinfo
        tar -C build/resources/main/static -zcf webapp.tgz .
        aws s3 cp --quiet webapp.tgz s3://${bucket}/deploy/webapp.tgz
        aws s3 cp --quiet $buildinfo s3://${bucket}/deploy/$buildinfo
      env: # Or as an environment variable
        bucket: ${{ secrets.AWS_DEPLOY_BUCKET_NAME }}
        buildinfo: webapp.buildinfo
